"""ipdate reservations table

Revision ID: 0599aefe54a8
Revises: d86a11256fb9
Create Date: 2024-11-11 21:40:42.583152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0599aefe54a8'
down_revision: Union[str, None] = 'd86a11256fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('payment_method', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'payment_method')
    # ### end Alembic commands ###
