"""add date to credit_purchases

Revision ID: a9034076a9fb
Revises: daa8bd1f00ba
Create Date: 2024-11-11 22:11:15.112635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9034076a9fb'
down_revision: Union[str, None] = 'daa8bd1f00ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_purchases', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_purchases', 'date')
    # ### end Alembic commands ###
